package com.murattel.app

data class Surah(val id: Int, val name: String)
data class Reader(val id: Int, val name: String, val server: String, val mushafId: Int)
data class Ayah(val verse: Int, val start: Double, val end: Double, val text: String)

object QuranData {
    val surahs = listOf(
        Surah(1, "الفاتحة"), Surah(2, "البقرة"), Surah(3, "آل عمران"), Surah(4, "النساء"),
        Surah(5, "المائدة"), Surah(6, "الأنعام"), Surah(7, "الأعراف"), Surah(8, "الأنفال"),
        Surah(9, "التوبة"), Surah(10, "يونس"), Surah(11, "هود"), Surah(12, "يوسف"),
        Surah(13, "الرعد"), Surah(14, "إبراهيم"), Surah(15, "الحجر"), Surah(16, "النحل"),
        Surah(17, "الإسراء"), Surah(18, "الكهف"), Surah(19, "مريم"), Surah(20, "طه"),
        Surah(21, "الأنبياء"), Surah(22, "الحج"), Surah(23, "المؤمنون"), Surah(24, "النور"),
        Surah(25, "الفرقان"), Surah(26, "الشعراء"), Surah(27, "النمل"), Surah(28, "القصص"),
        Surah(29, "العنكبوت"), Surah(30, "الروم"), Surah(31, "لقمان"), Surah(32, "السجدة"),
        Surah(33, "الأحزاب"), Surah(34, "سبأ"), Surah(35, "فاطر"), Surah(36, "يس"),
        Surah(37, "الصافات"), Surah(38, "ص"), Surah(39, "الزمر"), Surah(40, "غافر"),
        Surah(41, "فصلت"), Surah(42, "الشورى"), Surah(43, "الزخرف"), Surah(44, "الدخان"),
        Surah(45, "الجاثية"), Surah(46, "الأحقاف"), Surah(47, "محمد"), Surah(48, "الفتح"),
        Surah(49, "الحجرات"), Surah(50, "ق"), Surah(51, "الذاريات"), Surah(52, "الطور"),
        Surah(53, "النجم"), Surah(54, "القمر"), Surah(55, "الرحمن"), Surah(56, "الواقعة"),
        Surah(57, "الحديد"), Surah(58, "المجادلة"), Surah(59, "الحشر"), Surah(60, "الممتحنة"),
        Surah(61, "الصف"), Surah(62, "الجمعة"), Surah(63, "المنافقون"), Surah(64, "التغابن"),
        Surah(65, "الطلاق"), Surah(66, "التحريم"), Surah(67, "الملك"), Surah(68, "القلم"),
        Surah(69, "الحاقة"), Surah(70, "المعارج"), Surah(71, "نوح"), Surah(72, "الجن"),
        Surah(73, "المزمل"), Surah(74, "المدثر"), Surah(75, "القيامة"), Surah(76, "الإنسان"),
        Surah(77, "المرسلات"), Surah(78, "النبأ"), Surah(79, "النازعات"), Surah(80, "عبس"),
        Surah(81, "التكوير"), Surah(82, "الانفطار"), Surah(83, "المطففين"), Surah(84, "الانشقاق"),
        Surah(85, "البروج"), Surah(86, "الطارق"), Surah(87, "الأعلى"), Surah(88, "الغاشية"),
        Surah(89, "الفجر"), Surah(90, "البلد"), Surah(91, "الشمس"), Surah(92, "الليل"),
        Surah(93, "الضحى"), Surah(94, "الشرح"), Surah(95, "التين"), Surah(96, "العلق"),
        Surah(97, "القدر"), Surah(98, "البينة"), Surah(99, "الزلزلة"), Surah(100, "العاديات"),
        Surah(101, "القارعة"), Surah(102, "التكاثر"), Surah(103, "العصر"), Surah(104, "الهمزة"),
        Surah(105, "الفيل"), Surah(106, "قريش"), Surah(107, "الماعون"), Surah(108, "الكوثر"),
        Surah(109, "الكافرون"), Surah(110, "النصر"), Surah(111, "المسد"), Surah(112, "الإخلاص"),
        Surah(113, "الفلق"), Surah(114, "الناس")
    )

    val readers = listOf(
        Reader(1, "إبراهيم الأخضر", "https://server6.mp3quran.net/akdr/", 12),
        Reader(2, "أحمد الحواشي", "https://server6.mp3quran.net/hawashi/", 267),
        Reader(3, "أحمد الطرابلسي", "https://server6.mp3quran.net/atrablsi/", 166),
        Reader(4, "أحمد النعينع", "https://server6.mp3quran.net/nufais/", 14),
        Reader(5, "أحمد بن علي العجمي", "https://server6.mp3quran.net/ajm/", 79),
        Reader(6, "أكرم العلاقمي", "https://server6.mp3quran.net/akrm/", 167),
        Reader(7, "بندر بليلة", "https://server6.mp3quran.net/balilah/", 168),
        Reader(8, "توفيق الصائغ", "https://server6.mp3quran.net/tsfiq/", 51),
        Reader(9, "خالد الجليل", "https://server6.mp3quran.net/jleel/", 87),
        Reader(10, "خالد القحطاني", "https://server6.mp3quran.net/qht/", 47),
        Reader(11, "خالد المهنا", "https://server6.mp3quran.net/mahna/", 109),
        Reader(12, "زكي داغستاني", "https://server6.mp3quran.net/zaki/", 169),
        Reader(13, "سعد الغامدي", "https://server6.mp3quran.net/s_gmd/", 17),
        Reader(14, "سعود الشريم", "https://server6.mp3quran.net/shur/", 18),
        Reader(15, "صلاح البدير", "https://server6.mp3quran.net/budair/", 113),
        Reader(16, "صلاح الهاشم", "https://server6.mp3quran.net/hashim/", 170),
        Reader(17, "عبد الباسط عبد الصمد", "https://server6.mp3quran.net/basit/", 22),
        Reader(18, "عبد الرحمن السديس", "https://server6.mp3quran.net/sdis/", 19),
        Reader(19, "عبد الرحمن العوسي", "https://server6.mp3quran.net/aosi/", 171),
        Reader(20, "عبد الله الجهني", "https://server6.mp3quran.net/jhn/", 53),
        Reader(21, "عبد الله الموسى", "https://server6.mp3quran.net/mousa/", 172),
        Reader(22, "عبد الله بصفر", "https://server6.mp3quran.net/bsfr/", 29),
        Reader(23, "عبد الله خياط", "https://server6.mp3quran.net/kyat/", 30),
        Reader(24, "عبد المحسن الحارثي", "https://server6.mp3quran.net/harthi/", 115),
        Reader(25, "عبد المحسن القاسم", "https://server6.mp3quran.net/qasm/", 54),
        Reader(26, "علي الحذيفي", "https://server6.mp3quran.net/hudhaify/", 33),
        Reader(27, "علي جابر", "https://server6.mp3quran.net/a_jbr/", 31),
        Reader(28, "فارس عباد", "https://server6.mp3quran.net/frs_a/", 37),
        Reader(29, "ماهر المعيقلي", "https://server6.mp3quran.net/maher/", 24),
        Reader(30, "محمد أيوب", "https://server6.mp3quran.net/ayyub/", 25),
        Reader(31, "محمد البراك", "https://server6.mp3quran.net/barak/", 174),
        Reader(32, "محمد اللحيدان", "https://server6.mp3quran.net/lhdan/", 55),
        Reader(33, "محمد المحيسني", "https://server6.mp3quran.net/mhsny/", 116),
        Reader(34, "محمد جبريل", "https://server6.mp3quran.net/jbrl/", 26),
        Reader(35, "محمود الحصري", "https://server6.mp3quran.net/Husary/", 27),
        Reader(36, "محمود خليل الحصري (مجوّد)", "https://server6.mp3quran.net/Husary_Mujawwad/", 270),
        Reader(37, "مشاري العفاسي", "https://server6.mp3quran.net/afs/", 23),
        Reader(38, "ناصر القطامي", "https://server6.mp3quran.net/qtm/", 38),
        Reader(39, "نبيل الرفاعي", "https://server6.mp3quran.net/rifai/", 39),
        Reader(40, "هاني الرفاعي", "https://server6.mp3quran.net/hani/", 41),
        Reader(41, "ياسر الدوسري", "https://server6.mp3quran.net/yasser/", 42),
        Reader(42, "يوسف الشويعي", "https://server6.mp3quran.net/shoeairy/", 175)
    )
}
