import Foundation

// MARK: - All 114 Surahs
struct QuranData {
    static let surahs: [Surah] = [
        Surah(id: 1, name: "الفاتحة"), Surah(id: 2, name: "البقرة"), Surah(id: 3, name: "آل عمران"),
        Surah(id: 4, name: "النساء"), Surah(id: 5, name: "المائدة"), Surah(id: 6, name: "الأنعام"),
        Surah(id: 7, name: "الأعراف"), Surah(id: 8, name: "الأنفال"), Surah(id: 9, name: "التوبة"),
        Surah(id: 10, name: "يونس"), Surah(id: 11, name: "هود"), Surah(id: 12, name: "يوسف"),
        Surah(id: 13, name: "الرعد"), Surah(id: 14, name: "إبراهيم"), Surah(id: 15, name: "الحجر"),
        Surah(id: 16, name: "النحل"), Surah(id: 17, name: "الإسراء"), Surah(id: 18, name: "الكهف"),
        Surah(id: 19, name: "مريم"), Surah(id: 20, name: "طه"), Surah(id: 21, name: "الأنبياء"),
        Surah(id: 22, name: "الحج"), Surah(id: 23, name: "المؤمنون"), Surah(id: 24, name: "النور"),
        Surah(id: 25, name: "الفرقان"), Surah(id: 26, name: "الشعراء"), Surah(id: 27, name: "النمل"),
        Surah(id: 28, name: "القصص"), Surah(id: 29, name: "العنكبوت"), Surah(id: 30, name: "الروم"),
        Surah(id: 31, name: "لقمان"), Surah(id: 32, name: "السجدة"), Surah(id: 33, name: "الأحزاب"),
        Surah(id: 34, name: "سبأ"), Surah(id: 35, name: "فاطر"), Surah(id: 36, name: "يس"),
        Surah(id: 37, name: "الصافات"), Surah(id: 38, name: "ص"), Surah(id: 39, name: "الزمر"),
        Surah(id: 40, name: "غافر"), Surah(id: 41, name: "فصلت"), Surah(id: 42, name: "الشورى"),
        Surah(id: 43, name: "الزخرف"), Surah(id: 44, name: "الدّخان"), Surah(id: 45, name: "الجاثية"),
        Surah(id: 46, name: "الأحقاف"), Surah(id: 47, name: "محمد"), Surah(id: 48, name: "الفتح"),
        Surah(id: 49, name: "الحجرات"), Surah(id: 50, name: "ق"), Surah(id: 51, name: "الذاريات"),
        Surah(id: 52, name: "الطور"), Surah(id: 53, name: "النجم"), Surah(id: 54, name: "القمر"),
        Surah(id: 55, name: "الرحمن"), Surah(id: 56, name: "الواقعة"), Surah(id: 57, name: "الحديد"),
        Surah(id: 58, name: "المجادلة"), Surah(id: 59, name: "الحشر"), Surah(id: 60, name: "الممتحنة"),
        Surah(id: 61, name: "الصف"), Surah(id: 62, name: "الجمعة"), Surah(id: 63, name: "المنافقون"),
        Surah(id: 64, name: "التغابن"), Surah(id: 65, name: "الطلاق"), Surah(id: 66, name: "التحريم"),
        Surah(id: 67, name: "الملك"), Surah(id: 68, name: "القلم"), Surah(id: 69, name: "الحاقة"),
        Surah(id: 70, name: "المعارج"), Surah(id: 71, name: "نوح"), Surah(id: 72, name: "الجن"),
        Surah(id: 73, name: "المزمل"), Surah(id: 74, name: "المدثر"), Surah(id: 75, name: "القيامة"),
        Surah(id: 76, name: "الإنسان"), Surah(id: 77, name: "المرسلات"), Surah(id: 78, name: "النبأ"),
        Surah(id: 79, name: "النازعات"), Surah(id: 80, name: "عبس"), Surah(id: 81, name: "التكوير"),
        Surah(id: 82, name: "الإنفطار"), Surah(id: 83, name: "المطففين"), Surah(id: 84, name: "الإنشقاق"),
        Surah(id: 85, name: "البروج"), Surah(id: 86, name: "الطارق"), Surah(id: 87, name: "الأعلى"),
        Surah(id: 88, name: "الغاشية"), Surah(id: 89, name: "الفجر"), Surah(id: 90, name: "البلد"),
        Surah(id: 91, name: "الشمس"), Surah(id: 92, name: "الليل"), Surah(id: 93, name: "الضحى"),
        Surah(id: 94, name: "الشرح"), Surah(id: 95, name: "التين"), Surah(id: 96, name: "العلق"),
        Surah(id: 97, name: "القدر"), Surah(id: 98, name: "البينة"), Surah(id: 99, name: "الزلزلة"),
        Surah(id: 100, name: "العاديات"), Surah(id: 101, name: "القارعة"), Surah(id: 102, name: "التكاثر"),
        Surah(id: 103, name: "العصر"), Surah(id: 104, name: "الهمزة"), Surah(id: 105, name: "الفيل"),
        Surah(id: 106, name: "قريش"), Surah(id: 107, name: "الماعون"), Surah(id: 108, name: "الكوثر"),
        Surah(id: 109, name: "الكافرون"), Surah(id: 110, name: "النصر"), Surah(id: 111, name: "المسد"),
        Surah(id: 112, name: "الإخلاص"), Surah(id: 113, name: "الفلق"), Surah(id: 114, name: "الناس"),
    ]

    // MARK: - All Readers (from murattel website)
    static let readers: [Reader] = [
        Reader(id: 1, name: "إبراهيم الأخضر", server: "https://server6.mp3quran.net/akdr/", mushafId: 1),
        Reader(id: 10, name: "أكرم العلاقمي", server: "https://server9.mp3quran.net/akrm/", mushafId: 10),
        Reader(id: 102, name: "ماهر المعيقلي", server: "https://server12.mp3quran.net/maher/", mushafId: 102),
        Reader(id: 12, name: "إدريس أبكر", server: "https://server6.mp3quran.net/abkr/", mushafId: 12),
        Reader(id: 123, name: "مشاري العفاسي", server: "https://server8.mp3quran.net/afs/", mushafId: 123),
        Reader(id: 86, name: "ناصر القطامي", server: "https://server6.mp3quran.net/qtm/", mushafId: 86),
        Reader(id: 5, name: "أحمد بن علي العجمي", server: "https://server10.mp3quran.net/ajm/", mushafId: 5),
        Reader(id: 30, name: "سعد الغامدي", server: "https://server7.mp3quran.net/s_gmd/", mushafId: 30),
        Reader(id: 54, name: "عبدالرحمن السديس", server: "https://server11.mp3quran.net/sds/", mushafId: 54),
        Reader(id: 51, name: "عبدالباسط عبدالصمد", server: "https://server7.mp3quran.net/basit/", mushafId: 53),
        Reader(id: 118, name: "محمود خليل الحصري", server: "https://server13.mp3quran.net/husr/", mushafId: 118),
        Reader(id: 112, name: "محمد صديق المنشاوي", server: "https://server10.mp3quran.net/minsh/", mushafId: 112),
        Reader(id: 31, name: "سعود الشريم", server: "https://server7.mp3quran.net/shur/", mushafId: 31),
        Reader(id: 109, name: "محمد أيوب", server: "https://server8.mp3quran.net/ayyub/", mushafId: 109),
        Reader(id: 111, name: "محمد جبريل", server: "https://server8.mp3quran.net/jbrl/", mushafId: 111),
        Reader(id: 4, name: "شيخ أبو بكر الشاطري", server: "https://server11.mp3quran.net/shatri/", mushafId: 4),
        Reader(id: 81, name: "فارس عباد", server: "https://server8.mp3quran.net/frs_a/", mushafId: 81),
        Reader(id: 74, name: "علي بن عبدالرحمن الحذيفي", server: "https://server9.mp3quran.net/hthfi/", mushafId: 74),
        Reader(id: 62, name: "عبدالله عواد الجهني", server: "https://server13.mp3quran.net/jhn/", mushafId: 62),
        Reader(id: 89, name: "هاني الرفاعي", server: "https://server8.mp3quran.net/hani/", mushafId: 89),
        Reader(id: 92, name: "ياسر الدوسري", server: "https://server11.mp3quran.net/yasser/", mushafId: 92),
        Reader(id: 253, name: "إسلام صبحي", server: "https://server14.mp3quran.net/islam/Rewayat-Hafs-A-n-Assem/", mushafId: 253),
        Reader(id: 76, name: "علي جابر", server: "https://server11.mp3quran.net/a_jbr/", mushafId: 76),
        Reader(id: 121, name: "محمود علي البنا", server: "https://server8.mp3quran.net/bna/", mushafId: 121),
        Reader(id: 9, name: "أحمد نعينع", server: "https://server11.mp3quran.net/ahmad_nu/", mushafId: 9),
        Reader(id: 87, name: "نبيل الرفاعي", server: "https://server9.mp3quran.net/nabil/", mushafId: 87),
        Reader(id: 100, name: "ماجد العنزي", server: "https://server8.mp3quran.net/majd_onazi/", mushafId: 100),
        Reader(id: 105, name: "محمد البراك", server: "https://server13.mp3quran.net/braak/", mushafId: 105),
        Reader(id: 106, name: "محمد الطبلاوي", server: "https://server12.mp3quran.net/tblawi/", mushafId: 106),
        Reader(id: 107, name: "محمد اللحيدان", server: "https://server8.mp3quran.net/lhdan/", mushafId: 107),
        Reader(id: 108, name: "محمد المحيسني", server: "https://server11.mp3quran.net/mhsny/", mushafId: 108),
        Reader(id: 110, name: "محمد صالح عالم شاه", server: "https://server12.mp3quran.net/shah/", mushafId: 110),
        Reader(id: 115, name: "محمد عبدالكريم", server: "https://server12.mp3quran.net/m_krm/", mushafId: 115),
        Reader(id: 125, name: "مصطفى إسماعيل", server: "https://server8.mp3quran.net/mustafa/", mushafId: 125),
        Reader(id: 160, name: "عادل الكلباني", server: "https://server8.mp3quran.net/a_klb/", mushafId: 160),
        Reader(id: 162, name: "حسين آل الشيخ", server: "https://server11.mp3quran.net/alshaik/", mushafId: 162),
        Reader(id: 163, name: "حاتم فريد الواعر", server: "https://server11.mp3quran.net/hatem/", mushafId: 163),
        Reader(id: 217, name: "بندر بليله", server: "https://server6.mp3quran.net/balilah/", mushafId: 217),
        Reader(id: 221, name: "رعد محمد الكردي", server: "https://server6.mp3quran.net/kurdi/", mushafId: 221),
        Reader(id: 231, name: "هزاع البلوشي", server: "https://server11.mp3quran.net/hazza/", mushafId: 231),
        Reader(id: 245, name: "منصور السالمي", server: "https://server14.mp3quran.net/mansor/", mushafId: 245),
        Reader(id: 20, name: "خالد الجليل", server: "https://server10.mp3quran.net/jleel/", mushafId: 20),
        Reader(id: 21, name: "خالد القحطاني", server: "https://server10.mp3quran.net/qht/", mushafId: 21),
        Reader(id: 24, name: "خليفة الطنيجي", server: "https://server12.mp3quran.net/tnjy/", mushafId: 24),
        Reader(id: 225, name: "عبدالرحمن العوسي", server: "https://server6.mp3quran.net/aloosi/", mushafId: 225),
        Reader(id: 226, name: "خالد الغامدي", server: "https://server6.mp3quran.net/ghamdi/", mushafId: 226),
        Reader(id: 241, name: "محمد رفعت", server: "https://server14.mp3quran.net/refat/", mushafId: 241),
        Reader(id: 240, name: "سلمان العتيبي", server: "https://server11.mp3quran.net/salman/", mushafId: 240),
        Reader(id: 48, name: "عادل ريان", server: "https://server8.mp3quran.net/ryan/", mushafId: 48),
        Reader(id: 55, name: "عبدالعزيز الأحمد", server: "https://server11.mp3quran.net/a_ahmed/", mushafId: 55),
        Reader(id: 82, name: "فهد العتيبي", server: "https://server8.mp3quran.net/fahad_otibi/", mushafId: 82),
        Reader(id: 83, name: "فهد الكندري", server: "https://server11.mp3quran.net/kndri/", mushafId: 83),
        Reader(id: 7, name: "أحمد سعود", server: "https://server11.mp3quran.net/saud/", mushafId: 7),
        Reader(id: 8, name: "أحمد صابر", server: "https://server8.mp3quran.net/saber/", mushafId: 8),
        Reader(id: 6, name: "أحمد الحواشي", server: "https://server11.mp3quran.net/hawashi/", mushafId: 6),
        Reader(id: 3, name: "إبراهيم العسيري", server: "https://server6.mp3quran.net/3siri/", mushafId: 3),
        Reader(id: 2, name: "إبراهيم الجبرين", server: "https://server6.mp3quran.net/jbreen/", mushafId: 2),
        Reader(id: 35, name: "سامي الدوسري", server: "https://server8.mp3quran.net/sami_dosr/", mushafId: 35),
        Reader(id: 43, name: "صلاح البدير", server: "https://server6.mp3quran.net/s_bud/", mushafId: 43),
        Reader(id: 46, name: "صلاح بو خاطر", server: "https://server8.mp3quran.net/bu_khtr/", mushafId: 46),
        Reader(id: 67, name: "عبدالمحسن القاسم", server: "https://server8.mp3quran.net/qasm/", mushafId: 67),
        Reader(id: 90, name: "وليد الدليمي", server: "https://server8.mp3quran.net/dlami/", mushafId: 90),
        Reader(id: 36, name: "سيد رمضان", server: "https://server12.mp3quran.net/sayed/", mushafId: 36),
        Reader(id: 96, name: "يحيى حوا", server: "https://server12.mp3quran.net/yahya/", mushafId: 96),
        Reader(id: 97, name: "يوسف الشويعي", server: "https://server9.mp3quran.net/yousef/", mushafId: 97),
    ]
}
